#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Jan 15, 2020 05:30:28 PM CET  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #d7d8d9 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 500x400+672+223
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1055
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra43 \
        -borderwidth 3 -relief groove -background $vTcl(actual_gui_bg) \
        -height 300 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 419 
    vTcl:DefineAlias "$top.fra43" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra43
    button $site_3_0.but45 \
        -activebackground #ffd9da -activeforeground #ff8000 \
        -background #ffffff -command ent1 -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Rechercher 
    vTcl:DefineAlias "$site_3_0.but45" "search_button" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.but45
    entry $site_3_0.ent43 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent43" "search_bar" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.ent43
    label $site_3_0.lab46 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -text {Nom d'une entreprise :} 
    vTcl:DefineAlias "$site_3_0.lab46" "Label2" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.lab46
    radiobutton $site_3_0.rad50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {En ligne} 
    vTcl:DefineAlias "$site_3_0.rad50" "Radiobutton1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.rad50
    radiobutton $site_3_0.rad51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Hors ligne} 
    vTcl:DefineAlias "$site_3_0.rad51" "Radiobutton2" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.rad51
    place $site_3_0.but45 \
        -in $site_3_0 -x 160 -y 130 -width 66 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent43 \
        -in $site_3_0 -x 110 -y 80 -anchor nw -bordermode ignore 
    place $site_3_0.lab46 \
        -in $site_3_0 -x 130 -y 50 -anchor nw -bordermode ignore 
    place $site_3_0.rad50 \
        -in $site_3_0 -x 110 -y 100 -anchor nw -bordermode ignore 
    place $site_3_0.rad51 \
        -in $site_3_0 -x 190 -y 100 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.fra43
    label $top.lab47 \
        -background $vTcl(actual_gui_bg) \
        -font {-family {Lato} -size 36 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor #636363 \
        -text Scrapper -width 234 
    vTcl:DefineAlias "$top.lab47" "Label3" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.lab47
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra43 \
        -in $top -x 50 -y 75 -width 400 -relwidth 0 -height 250 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 120 -y 10 -width 250 -relwidth 0 -height 50 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

